USE KOPARDE;
SELECT * FROM OLYMPIC_RECORDS;
-- NO. OF MALE,FEMALE PARTICIPATED IN EVERY OLYMPIC
CREATE VIEW MALE_FEMALE_COUNT AS
SELECT YEAR,SEX,COUNT(SEX) FROM OLYMPIC_RECORDS
GROUP BY YEAR,SEX
ORDER BY YEAR;

-- WHICH TEAM HAS WON THE MOST MEDALS
CREATE VIEW HIGHEST_MEDAL_WINNING_TEAM AS
SELECT TEAM,COUNT(MEDAL) FROM OLYMPIC_RECORDS
WHERE MEDAL!="NOMEADAL"
GROUP BY TEAM
ORDER BY 2 DESC
LIMIT 1;
SELECT * FROM HIGHEST_MEDAL_WINNING_TEAM;

-- WHICH PLAYER HA WON MOST MEDALS
CREATE VIEW  MOST_MEDAL_WINNING_PLAYER AS
SELECT NAME,COUNT(MEDAL) FROM OLYMPIC_RECORDS
WHERE MEDAL="NOMEDAL"
GROUP BY NAME
ORDER BY 2 DESC;

-- IN WHICH VENUE MOST OLYMPIC GAMES TOOK PLACE
CREATE VIEW VENUES AS
 SELECT CITY,COUNT(CITY) FROM OLYMPIC_RECORDS
 GROUP BY CITY
 ORDER BY 2 DESC;
 
 -- CREATE DIFFERENT  AGE GROUP AND FIND OUT WHICH AGE GROUP HAS WON THE MOST MEDALS
 CREATE VIEW AGE_GROUP_MEDAL AS
WITH CTE AS  (SELECT AGE,MEDAL,CASE WHEN AGE>14 AND AGE <=30 THEN "14-30"
                        WHEN AGE>30 AND AGE <=45 THEN "30-45"
                        ELSE "ABOVE_45" END AS AGE_GROUP  FROM OLYMPIC_RECORDS)
                        SELECT AGE_GROUP,COUNT(MEDAL) FROM CTE 
                        WHERE MEDAL!="NOMEADAL"
                        GROUP BY AGE_GROUP;
                        
-- WHICH TEAM HAS WON THE MOST GOLD MELAS IN SPECIFIC SPORT
 
 CREATE VIEW  GOLD_WINNING_TEAM AS
 SELECT TEAM,SPORT,COUNT(MEDAL) AS GOLDS FROM OLYMPIC_RECORDS
 WHERE MEDAL="GOLD"
 GROUP BY TEAM,SPORT
 ORDER BY GOLDS DESC
 LIMIT 1;
                        
-- TEAMS WITH NO. OF MEDAL WINNING

SELECT TEAM,MEDAL,COUNT(MEDAL) FROM OLYMPIC_RECORDS
WHERE MEDAL!="NOMEDAL"
GROUP BY TEAM ,MEDAL
ORDER BY TEAM ;

-- HIGHEST MEDALS WON BY  TEAMS IN  DIFFERENT SPORTS

WITH CTT AS (SELECT TEAM,SPORT,COUNT(MEDAL),ROW_NUMBER() OVER(PARTITION BY TEAM ORDER BY COUNT(MEDAL) DESC) AS RNK FROM OLYMPIC_RECORDS
WHERE MEDAL="NOMEDAL"
GROUP BY TEAM, SPORT
ORDER BY TEAM,SPORT,3 DESC)
SELECT * FROM CTT 
WHERE RNK=1;


